import { useCallback } from "react";
import { useAuthStore } from "@/store";

export type SavingsAction =
  | "CREATE"
  | "APPROVE"
  | "ACTIVATE"
  | "REJECT"
  | "WITHDRAW"
  | "UNDO_APPROVAL"
  | "CLOSE"
  | "DELETE"
  | "DEPOSIT"
  | "WITHDRAWAL"
  | "HOLDAMOUNT"
  | "RELEASEAMOUNT"
  | "ADJUST"
  | "APPLYANNUALFEE"
  | "CALCULATEINTEREST"
  | "POSTINTEREST"
  | "BLOCK"
  | "UNBLOCK"
  | "ASSIGNOFFICER"
  | "UNASSIGNOFFICER";

export const SAVINGS_ACTION_PERMISSIONS: Record<SavingsAction, string> = {
  CREATE: "CREATE_SAVINGSACCOUNT",
  APPROVE: "APPROVE_SAVINGSACCOUNT",
  ACTIVATE: "ACTIVATE_SAVINGSACCOUNT",
  REJECT: "REJECT_SAVINGSACCOUNT",
  WITHDRAW: "WITHDRAW_SAVINGSACCOUNT",
  UNDO_APPROVAL: "APPROVALUNDO_SAVINGSACCOUNT",
  CLOSE: "CLOSE_SAVINGSACCOUNT",
  DELETE: "DELETE_SAVINGSACCOUNT",
  DEPOSIT: "DEPOSIT_SAVINGSACCOUNT",
  WITHDRAWAL: "WITHDRAWAL_SAVINGSACCOUNT",
  HOLDAMOUNT: "HOLDAMOUNT_SAVINGSACCOUNT",
  RELEASEAMOUNT: "RELEASEAMOUNT_SAVINGSACCOUNT",
  ADJUST: "ADJUSTTRANSACTION_SAVINGSACCOUNT",
  APPLYANNUALFEE: "APPLYANNUALFEE_SAVINGSACCOUNT",
  CALCULATEINTEREST: "CALCULATEINTEREST_SAVINGSACCOUNT",
  POSTINTEREST: "POSTINTEREST_SAVINGSACCOUNT",
  BLOCK: "BLOCK_SAVINGSACCOUNT",
  UNBLOCK: "UNBLOCK_SAVINGSACCOUNT",
  ASSIGNOFFICER: "UPDATESAVINGSOFFICER_SAVINGSACCOUNT",
  UNASSIGNOFFICER: "REMOVESAVINGSOFFICER_SAVINGSACCOUNT",
};

export function useSavingsPermissions() {
  const permissions = useAuthStore((s) => s.user?.permissions ?? []);

  const hasPermission = useCallback(
    (action: SavingsAction) => {
      const code = SAVINGS_ACTION_PERMISSIONS[action];
      return permissions.includes(code);
    },
    [permissions],
  );

  return { hasPermission, permissions };
}
